[project]
name = "LearnWebGPU-Code"
version = "0.1.0"
description = "Add a short description here"
authors = ["linuxing3 <linuxing3@qq.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
glfw = "3.3.9.*"
glm = "0.9.9.8.*"
wgpu-native = ">=0.18.1.4,<0.18.2"
