[project]
name = "LearnWebGPU-Code"
version = "0.1.0"
description = "Add a short description here"
authors = ["linuxing3 <linuxing3@qq.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
build = "cmake -B build && cmake --build build"
start = "./build/App"

[dependencies]
glfw = "3.3.9.*"
glm = "0.9.9.8.*"
